---
json_rpc_url: "http://localhost:8899"
websocket_url: ""
keypair_path: "./.config/testUser-super-keypair.json"
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed
